#!/bin/bash

#SBATCH -A IscrC_FairLLM
#SBATCH -p boost_usr_prod
#SBATCH --time 24:00:00      # format: HH:MM:SS
#SBATCH -N 1                 # 1 node
#SBATCH --ntasks-per-node=32 # 8 tasks out of 32
#SBATCH --job-name=hada_benchmark_txtflow
#SBATCH --output=slurm-%j_leonardo.out
#SBATCH --error=slurm-%j_leonardo.err

module load python/3.11.6--gcc--8.5.0
source hada_benchmark/bin/activate
python3 main.py -e ./build/demo -d data/export/bone.n26c100.max.bbk -a bk
python3 main.py -e ./build/demo -d data/export/bone.n26c100.max.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/bone.n26c100.max.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/bone.n26c100.max.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/bone.n26c100.max.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/bone.n26c100.max.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/bone.n26c10.max.bbk -a bk
python3 main.py -e ./build/demo -d data/export/bone.n26c10.max.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/bone.n26c10.max.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/bone.n26c10.max.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/bone.n26c10.max.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/bone.n26c10.max.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/bone.n6c100.max.bbk -a bk
python3 main.py -e ./build/demo -d data/export/bone.n6c100.max.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/bone.n6c100.max.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/bone.n6c100.max.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/bone.n6c100.max.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/bone.n6c100.max.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/bone.n6c10.max.bbk -a bk
python3 main.py -e ./build/demo -d data/export/bone.n6c10.max.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/bone.n6c10.max.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/bone.n6c10.max.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/bone.n6c10.max.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/bone.n6c10.max.bbk -a eibfs_i_nr