#!/bin/bash

#SBATCH -A IscrC_FairLLM
#SBATCH -p boost_usr_prod
#SBATCH --time 24:00:00      # format: HH:MM:SS
#SBATCH -N 1                 # 1 node
#SBATCH --ntasks-per-node=32 # 8 tasks out of 32
#SBATCH --job-name=hada_benchmark_txtflow
#SBATCH --output=deeplogismos_leonardo.out
#SBATCH --error=deeplogismos_leonardo.err

module load python/3.11.6--gcc--8.5.0
source hada_benchmark/bin/activate
python3 main.py -e ./build/demo -d data/export/deeplogismos.1.bbk -a bk
python3 main.py -e ./build/demo -d data/export/deeplogismos.1.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/deeplogismos.1.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/deeplogismos.1.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/deeplogismos.1.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/deeplogismos.1.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/deeplogismos.2.bbk -a bk
python3 main.py -e ./build/demo -d data/export/deeplogismos.2.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/deeplogismos.2.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/deeplogismos.2.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/deeplogismos.2.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/deeplogismos.2.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/deeplogismos.3.bbk -a bk
python3 main.py -e ./build/demo -d data/export/deeplogismos.3.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/deeplogismos.3.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/deeplogismos.3.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/deeplogismos.3.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/deeplogismos.3.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/deeplogismos.4.bbk -a bk
python3 main.py -e ./build/demo -d data/export/deeplogismos.4.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/deeplogismos.4.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/deeplogismos.4.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/deeplogismos.4.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/deeplogismos.4.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/deeplogismos.5.bbk -a bk
python3 main.py -e ./build/demo -d data/export/deeplogismos.5.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/deeplogismos.5.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/deeplogismos.5.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/deeplogismos.5.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/deeplogismos.5.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/deeplogismos.6.bbk -a bk
python3 main.py -e ./build/demo -d data/export/deeplogismos.6.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/deeplogismos.6.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/deeplogismos.6.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/deeplogismos.6.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/deeplogismos.6.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/deeplogismos.7.bbk -a bk
python3 main.py -e ./build/demo -d data/export/deeplogismos.7.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/deeplogismos.7.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/deeplogismos.7.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/deeplogismos.7.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/deeplogismos.7.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/deeplogismos.8.bbk -a bk
python3 main.py -e ./build/demo -d data/export/deeplogismos.8.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/deeplogismos.8.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/deeplogismos.8.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/deeplogismos.8.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/deeplogismos.8.bbk -a eibfs_i_nr