#!/bin/bash

#SBATCH -A IscrC_FairLLM
#SBATCH -p boost_usr_prod
#SBATCH --time 24:00:00      # format: HH:MM:SS
#SBATCH -N 1                 # 1 node
#SBATCH --ntasks-per-node=32 # 8 tasks out of 32
#SBATCH --job-name=hada_benchmark_txtflow
#SBATCH --output=slurm-%j_leonardo.out
#SBATCH --error=slurm-%j_leonardo.err

module load python/3.11.6--gcc--8.5.0
source hada_benchmark/bin/activate
python3 main.py -e ./build/demo -d data/export/simcells.sd2.bq -a bk
python3 main.py -e ./build/demo -d data/export/simcells.sd2.bq -a mbk
python3 main.py -e ./build/demo -d data/export/simcells.sd2.bq -a mbk_r
python3 main.py -e ./build/demo -d data/export/simcells.sd2.bq -a eibfs
python3 main.py -e ./build/demo -d data/export/simcells.sd2.bq -a eibfs_i
python3 main.py -e ./build/demo -d data/export/simcells.sd2.bq -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/simcells.sd3.bq -a bk
python3 main.py -e ./build/demo -d data/export/simcells.sd3.bq -a mbk
python3 main.py -e ./build/demo -d data/export/simcells.sd3.bq -a mbk_r
python3 main.py -e ./build/demo -d data/export/simcells.sd3.bq -a eibfs
python3 main.py -e ./build/demo -d data/export/simcells.sd3.bq -a eibfs_i
python3 main.py -e ./build/demo -d data/export/simcells.sd3.bq -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/super_res-E1.txt.bbk -a bk
python3 main.py -e ./build/demo -d data/export/super_res-E1.txt.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/super_res-E1.txt.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/super_res-E1.txt.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/super_res-E1.txt.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/super_res-E1.txt.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/super_res-Paper1.txt.bbk -a bk
python3 main.py -e ./build/demo -d data/export/super_res-Paper1.txt.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/super_res-Paper1.txt.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/super_res-Paper1.txt.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/super_res-Paper1.txt.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/super_res-Paper1.txt.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/superres_graph.txt.bbk -a bk
python3 main.py -e ./build/demo -d data/export/superres_graph.txt.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/superres_graph.txt.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/superres_graph.txt.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/superres_graph.txt.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/superres_graph.txt.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/texture-Cremer.txt.bbk -a bk
python3 main.py -e ./build/demo -d data/export/texture-Cremer.txt.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/texture-Cremer.txt.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/texture-Cremer.txt.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/texture-Cremer.txt.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/texture-Cremer.txt.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/texture-OLD-D103.txt.bbk -a bk
python3 main.py -e ./build/demo -d data/export/texture-OLD-D103.txt.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/texture-OLD-D103.txt.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/texture-OLD-D103.txt.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/texture-OLD-D103.txt.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/texture-OLD-D103.txt.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/texture-Paper1.txt.bbk -a bk
python3 main.py -e ./build/demo -d data/export/texture-Paper1.txt.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/texture-Paper1.txt.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/texture-Paper1.txt.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/texture-Paper1.txt.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/texture-Paper1.txt.bbk -a eibfs_i_nr
python3 main.py -e ./build/demo -d data/export/texture-Temp.txt.bbk -a bk
python3 main.py -e ./build/demo -d data/export/texture-Temp.txt.bbk -a mbk
python3 main.py -e ./build/demo -d data/export/texture-Temp.txt.bbk -a mbk_r
python3 main.py -e ./build/demo -d data/export/texture-Temp.txt.bbk -a eibfs
python3 main.py -e ./build/demo -d data/export/texture-Temp.txt.bbk -a eibfs_i
python3 main.py -e ./build/demo -d data/export/texture-Temp.txt.bbk -a eibfs_i_nr